[package]
name = "urcu-sys"
version = "0.0.5"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]
edition = "2018"
license = "LGPL-2.1"
description = "System bindings for urcu (user-space rcu)"
readme = "README.md"
keywords = ["rcu", "parallel", "read-copy-update", "linux"]
categories = ["algorithms", "concurrency", "data-structures", "os"]
links = "urcu"
repository = "https://github.com/gz/urcu-sys"

[package.metadata.pkg-config]
liburcu = "0.11"
liburcu-qsbr = "0.11"
liburcu-cds = "0.11"

[build-dependencies]
bindgen = "0.51"
metadeps = "1.1.2"

[features]
# there are multiple flavors of liburcu. Currently implemented : memb (default) and qsbr.
default = [ "memb" ]
memb = []
qsbr = []